"Filed out from Dolphin Smalltalk 7"!

PMBOKProcessConnector subclass: #PMBOKOutput
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKOutput guid: (GUID fromString: '{b5eb1dcf-cbcb-4a3f-bdbe-090dcca8948d}')!
PMBOKOutput comment: ''!
!PMBOKOutput categoriesForClass!Kernel-Objects! !
!PMBOKOutput methodsFor!

pathName

	^'Output'! !
!PMBOKOutput categoriesFor: #pathName!public! !

!PMBOKOutput class methodsFor!

icon
	^PMBOKOutputDefinition icon! !
!PMBOKOutput class categoriesFor: #icon!public! !

