"Filed out from Dolphin Smalltalk 7"!

PMBOKDocumentEvent subclass: #PMBOKPublishEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKPublishEvent guid: (GUID fromString: '{48e5ec61-8dee-451e-ad0f-3cffab2a7f2b}')!
PMBOKPublishEvent comment: ''!
!PMBOKPublishEvent categoriesForClass!Kernel-Objects! !
!PMBOKPublishEvent methodsFor!

eventName

	^'Publish'! !
!PMBOKPublishEvent categoriesFor: #eventName!public! !

