"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKHumanResourceManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKHumanResourceManagement guid: (GUID fromString: '{e17d1131-075a-471e-b3b0-016fecdccff7}')!
PMBOKHumanResourceManagement comment: ''!
!PMBOKHumanResourceManagement categoriesForClass!Kernel-Objects! !
!PMBOKHumanResourceManagement methodsFor!

chapterNumber

	^9!

englishAreaName
	^'HUMAN RESOURCE'!

spanishAreaName
	^'Recursos Humanos'! !
!PMBOKHumanResourceManagement categoriesFor: #chapterNumber!public! !
!PMBOKHumanResourceManagement categoriesFor: #englishAreaName!public! !
!PMBOKHumanResourceManagement categoriesFor: #spanishAreaName!public! !

