"Filed out from Dolphin Smalltalk 7"!

PMIObject subclass: #PMBOKObjectDefinition
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKObjectDefinition guid: (GUID fromString: '{f630a5b5-08a7-4dee-ac12-4554724c7d3b}')!
PMBOKObjectDefinition comment: ''!
!PMBOKObjectDefinition categoriesForClass!Kernel-Objects! !
!PMBOKObjectDefinition methodsFor!

deliverableDescription
	^''!

getAllProcesses

	^self projectModel getAllProcesses!

isProcessDefinition

	^false! !
!PMBOKObjectDefinition categoriesFor: #deliverableDescription!public! !
!PMBOKObjectDefinition categoriesFor: #getAllProcesses!public! !
!PMBOKObjectDefinition categoriesFor: #isProcessDefinition!public! !

