"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKCostManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKCostManagement guid: (GUID fromString: '{2f853d09-9c07-4f78-9469-a31af26e2423}')!
PMBOKCostManagement comment: ''!
!PMBOKCostManagement categoriesForClass!Kernel-Objects! !
!PMBOKCostManagement methodsFor!

chapterNumber

	^7!

englishAreaName
	^'COST'!

spanishAreaName
	^'Costo'! !
!PMBOKCostManagement categoriesFor: #chapterNumber!public! !
!PMBOKCostManagement categoriesFor: #englishAreaName!public! !
!PMBOKCostManagement categoriesFor: #spanishAreaName!public! !

