"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKCommunicationManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKCommunicationManagement guid: (GUID fromString: '{9337c3a3-8125-48da-b226-3f0d573b4f6b}')!
PMBOKCommunicationManagement comment: ''!
!PMBOKCommunicationManagement categoriesForClass!Kernel-Objects! !
!PMBOKCommunicationManagement methodsFor!

chapterNumber

	^10!

englishAreaName
	^'COMMUNICATIONS'!

spanishAreaName
	^'Comunicaciones'! !
!PMBOKCommunicationManagement categoriesFor: #chapterNumber!public! !
!PMBOKCommunicationManagement categoriesFor: #englishAreaName!public! !
!PMBOKCommunicationManagement categoriesFor: #spanishAreaName!public! !

