"Filed out from Dolphin Smalltalk 7"!

PMBOKArtifactDefinition subclass: #PMBOKProductServiceDefinition
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKProductServiceDefinition guid: (GUID fromString: '{2765859e-cf26-4c3f-9bd2-326349cf7f95}')!
PMBOKProductServiceDefinition comment: ''!
!PMBOKProductServiceDefinition categoriesForClass!Kernel-Objects! !
!PMBOKProductServiceDefinition methodsFor!

printType

	^self defaultLanguage printProductServiceType: self! !
!PMBOKProductServiceDefinition categoriesFor: #printType!public! !

!PMBOKProductServiceDefinition class methodsFor!

icon

	^IUnknown icon!

printType

	^self defaultLanguage printProductServiceType: self! !
!PMBOKProductServiceDefinition class categoriesFor: #icon!public! !
!PMBOKProductServiceDefinition class categoriesFor: #printType!public! !

