"Filed out from Dolphin Smalltalk 7"!

PMBOKManagementProcessGroup subclass: #PMBOKClosingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKClosingGroup guid: (GUID fromString: '{2a0ced58-f460-4d2e-bbdd-62969f03f8ba}')!
PMBOKClosingGroup comment: ''!
!PMBOKClosingGroup categoriesForClass!Kernel-Objects! !
!PMBOKClosingGroup methodsFor!

englishGroupName

	^'Closing'!

spanishGroupName
	^'Cierre'! !
!PMBOKClosingGroup categoriesFor: #englishGroupName!public! !
!PMBOKClosingGroup categoriesFor: #spanishGroupName!public! !

