"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKScopeManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKScopeManagement guid: (GUID fromString: '{66c2b75b-f117-4a03-bcdb-b4ad69c9532e}')!
PMBOKScopeManagement comment: ''!
!PMBOKScopeManagement categoriesForClass!Kernel-Objects! !
!PMBOKScopeManagement methodsFor!

chapterNumber

	^5!

englishAreaName
	^'SCOPE'!

spanishAreaName
	^'Alcance'! !
!PMBOKScopeManagement categoriesFor: #chapterNumber!public! !
!PMBOKScopeManagement categoriesFor: #englishAreaName!public! !
!PMBOKScopeManagement categoriesFor: #spanishAreaName!public! !

