"Filed out from Dolphin Smalltalk 7"!

PMBOKIExecutionPath subclass: #PMBOKArtifactExecutionPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKArtifactExecutionPath guid: (GUID fromString: '{aa1bdd6b-ba9f-418a-bc85-7dc2f9de4270}')!
PMBOKArtifactExecutionPath comment: ''!
!PMBOKArtifactExecutionPath categoriesForClass!Kernel-Objects! !
