"Filed out from Dolphin Smalltalk 7"!

PMBOKManagementProcessGroup subclass: #PMBOKInitiatingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKInitiatingGroup guid: (GUID fromString: '{db794c59-f6ea-4bbe-9fed-96d4a02bd1ac}')!
PMBOKInitiatingGroup comment: ''!
!PMBOKInitiatingGroup categoriesForClass!Kernel-Objects! !
!PMBOKInitiatingGroup methodsFor!

englishGroupName

	^'Initiating'!

spanishGroupName
	^'Iniciación'! !
!PMBOKInitiatingGroup categoriesFor: #englishGroupName!public! !
!PMBOKInitiatingGroup categoriesFor: #spanishGroupName!public! !

