"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKTimeManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKTimeManagement guid: (GUID fromString: '{f193a182-e312-4ada-9fbf-3f5bd00bb404}')!
PMBOKTimeManagement comment: ''!
!PMBOKTimeManagement categoriesForClass!Kernel-Objects! !
!PMBOKTimeManagement methodsFor!

chapterNumber

	^6!

englishAreaName
	^'TIME'!

spanishAreaName
	^'Tiempo'! !
!PMBOKTimeManagement categoriesFor: #chapterNumber!public! !
!PMBOKTimeManagement categoriesFor: #englishAreaName!public! !
!PMBOKTimeManagement categoriesFor: #spanishAreaName!public! !

