"Filed out from Dolphin Smalltalk 7"!

PMIObject subclass: #PMBOKProcessesBuilder
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: 'default'!
PMBOKProcessesBuilder guid: (GUID fromString: '{f55667e1-44c7-4dd9-8541-065e326fc2cd}')!
PMBOKProcessesBuilder comment: ''!
!PMBOKProcessesBuilder categoriesForClass!Kernel-Objects! !
!PMBOKProcessesBuilder class methodsFor!

default
	^default!

default: anObject
	default := anObject! !
!PMBOKProcessesBuilder class categoriesFor: #default!accessing!private! !
!PMBOKProcessesBuilder class categoriesFor: #default:!accessing!private! !

