"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKRiskManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKRiskManagement guid: (GUID fromString: '{1f41c9d0-4872-4b30-bbc5-2fb3faf9b54f}')!
PMBOKRiskManagement comment: ''!
!PMBOKRiskManagement categoriesForClass!Kernel-Objects! !
!PMBOKRiskManagement methodsFor!

chapterNumber

	^11!

englishAreaName
	^'RISK'!

spanishAreaName
	^'Riesgo'! !
!PMBOKRiskManagement categoriesFor: #chapterNumber!public! !
!PMBOKRiskManagement categoriesFor: #englishAreaName!public! !
!PMBOKRiskManagement categoriesFor: #spanishAreaName!public! !

