"Filed out from Dolphin Smalltalk 7"!

PMBOKIExecutionPath subclass: #PMBOKChangeRequestExecutionPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKChangeRequestExecutionPath guid: (GUID fromString: '{37120efe-fef3-4abc-a1d7-1af734defce3}')!
PMBOKChangeRequestExecutionPath comment: ''!
!PMBOKChangeRequestExecutionPath categoriesForClass!Kernel-Objects! !
