"Filed out from Dolphin Smalltalk 7"!

PMBOKDocumentEvent subclass: #PMBOKUpdateVersionEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKUpdateVersionEvent guid: (GUID fromString: '{1179eed1-4c42-44a4-939d-9e753db2a94f}')!
PMBOKUpdateVersionEvent comment: ''!
!PMBOKUpdateVersionEvent categoriesForClass!Kernel-Objects! !
!PMBOKUpdateVersionEvent methodsFor!

eventName

	^'Update'! !
!PMBOKUpdateVersionEvent categoriesFor: #eventName!public! !

