"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKQualityManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKQualityManagement guid: (GUID fromString: '{b7b7a031-277b-4652-9bc6-a8bf4b9d69bf}')!
PMBOKQualityManagement comment: ''!
!PMBOKQualityManagement categoriesForClass!Kernel-Objects! !
!PMBOKQualityManagement methodsFor!

chapterNumber

	^8!

englishAreaName
	^'QUALITY'!

spanishAreaName
	^'Calidad'! !
!PMBOKQualityManagement categoriesFor: #chapterNumber!public! !
!PMBOKQualityManagement categoriesFor: #englishAreaName!public! !
!PMBOKQualityManagement categoriesFor: #spanishAreaName!public! !

