"Filed out from Dolphin Smalltalk 7"!

PMBOKManagementProcessGroup subclass: #PMBOKExecutingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKExecutingGroup guid: (GUID fromString: '{9f8732bf-7b4c-4e5d-a712-b8295db84f9f}')!
PMBOKExecutingGroup comment: ''!
!PMBOKExecutingGroup categoriesForClass!Kernel-Objects! !
!PMBOKExecutingGroup methodsFor!

englishGroupName

	^'Executing'!

spanishGroupName
	^'Ejecución'! !
!PMBOKExecutingGroup categoriesFor: #englishGroupName!public! !
!PMBOKExecutingGroup categoriesFor: #spanishGroupName!public! !

