"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKProcurementManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKProcurementManagement guid: (GUID fromString: '{7d9022cf-6424-4a1b-8b42-c935b1194a86}')!
PMBOKProcurementManagement comment: ''!
!PMBOKProcurementManagement categoriesForClass!Kernel-Objects! !
!PMBOKProcurementManagement methodsFor!

chapterNumber

	^12!

englishAreaName
	^'PROCUREMENT'!

spanishAreaName
	^'Adquisiciones'! !
!PMBOKProcurementManagement categoriesFor: #chapterNumber!public! !
!PMBOKProcurementManagement categoriesFor: #englishAreaName!public! !
!PMBOKProcurementManagement categoriesFor: #spanishAreaName!public! !

