"Filed out from Dolphin Smalltalk 7"!

PMBOKProgram subclass: #PMBOKLowerLevelProgram
	instanceVariableNames: 'parentProgram'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKLowerLevelProgram guid: (GUID fromString: '{b3abc2a5-fc62-4ee1-862c-8878bcf884f4}')!
PMBOKLowerLevelProgram comment: ''!
!PMBOKLowerLevelProgram categoriesForClass!Kernel-Objects! !
!PMBOKLowerLevelProgram methodsFor!

parentProgram
	^parentProgram!

parentProgram: anObject
	parentProgram := anObject!

pathName

	^'Lower Level Program'! !
!PMBOKLowerLevelProgram categoriesFor: #parentProgram!accessing!private! !
!PMBOKLowerLevelProgram categoriesFor: #parentProgram:!accessing!private! !
!PMBOKLowerLevelProgram categoriesFor: #pathName!public! !

