"Filed out from Dolphin Smalltalk 7"!

PMBOKManagementProcessGroup subclass: #PMBOKPlanningGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKPlanningGroup guid: (GUID fromString: '{158b5b71-dbc4-46d0-8a84-27e882df7aec}')!
PMBOKPlanningGroup comment: ''!
!PMBOKPlanningGroup categoriesForClass!Kernel-Objects! !
!PMBOKPlanningGroup methodsFor!

englishGroupName

	^'Planning'!

spanishGroupName
	^'Planificación'! !
!PMBOKPlanningGroup categoriesFor: #englishGroupName!public! !
!PMBOKPlanningGroup categoriesFor: #spanishGroupName!public! !

