"Filed out from Dolphin Smalltalk 7"!

PMBOKKnowledgeArea subclass: #PMBOKIntegrationManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKIntegrationManagement guid: (GUID fromString: '{1d0ff8cc-e370-4b3d-ba60-02c1629553ad}')!
PMBOKIntegrationManagement comment: ''!
!PMBOKIntegrationManagement categoriesForClass!Kernel-Objects! !
!PMBOKIntegrationManagement methodsFor!

chapterNumber

	^4!

englishAreaName
	^'INTEGRATION'!

spanishAreaName
	^'Integración'! !
!PMBOKIntegrationManagement categoriesFor: #chapterNumber!public! !
!PMBOKIntegrationManagement categoriesFor: #englishAreaName!public! !
!PMBOKIntegrationManagement categoriesFor: #spanishAreaName!public! !

