"Filed out from Dolphin Smalltalk 7"!

PMBOKDocumentEvent subclass: #PMBOKCreateVersionEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKCreateVersionEvent guid: (GUID fromString: '{28ec7ac2-d139-42e6-b416-e1420d42b133}')!
PMBOKCreateVersionEvent comment: ''!
!PMBOKCreateVersionEvent categoriesForClass!Kernel-Objects! !
!PMBOKCreateVersionEvent methodsFor!

eventName

	^'Creation'! !
!PMBOKCreateVersionEvent categoriesFor: #eventName!public! !

