"Filed out from Dolphin Smalltalk 7"!

PMBOKManagementProcessGroup subclass: #PMBOKMonitoringControllingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMBOKMonitoringControllingGroup guid: (GUID fromString: '{2b3be8fb-e3bb-493b-a380-0d92d741ef2e}')!
PMBOKMonitoringControllingGroup comment: ''!
!PMBOKMonitoringControllingGroup categoriesForClass!Kernel-Objects! !
!PMBOKMonitoringControllingGroup methodsFor!

englishGroupName

	^'Monitoring and Controlling'!

spanishGroupName
	^'Seguimiento y Control'! !
!PMBOKMonitoringControllingGroup categoriesFor: #englishGroupName!public! !
!PMBOKMonitoringControllingGroup categoriesFor: #spanishGroupName!public! !

