"Filed out from Dolphin Smalltalk 7"!

PMIExecutionPath subclass: #PMIChangeRequestExecutionPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIChangeRequestExecutionPath guid: (GUID fromString: '{37120efe-fef3-4abc-a1d7-1af734defce3}')!
PMIChangeRequestExecutionPath comment: ''!
!PMIChangeRequestExecutionPath categoriesForClass!Kernel-Objects! !
