"Filed out from Dolphin Smalltalk 7"!

PMIManagementProcessGroup subclass: #PMIClosingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIClosingGroup guid: (GUID fromString: '{2a0ced58-f460-4d2e-bbdd-62969f03f8ba}')!
PMIClosingGroup comment: ''!
!PMIClosingGroup categoriesForClass!Kernel-Objects! !
!PMIClosingGroup methodsFor!

englishGroupName

	^'Closing'!

spanishGroupName
	^'Cierre'! !
!PMIClosingGroup categoriesFor: #englishGroupName!public! !
!PMIClosingGroup categoriesFor: #spanishGroupName!public! !

