"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMICostManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMICostManagement guid: (GUID fromString: '{2f853d09-9c07-4f78-9469-a31af26e2423}')!
PMICostManagement comment: ''!
!PMICostManagement categoriesForClass!Kernel-Objects! !
!PMICostManagement methodsFor!

chapterNumber

	^7!

englishAreaName
	^'COST'!

spanishAreaName
	^'Costo'! !
!PMICostManagement categoriesFor: #chapterNumber!public! !
!PMICostManagement categoriesFor: #englishAreaName!public! !
!PMICostManagement categoriesFor: #spanishAreaName!public! !

