"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMICommunicationManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMICommunicationManagement guid: (GUID fromString: '{9337c3a3-8125-48da-b226-3f0d573b4f6b}')!
PMICommunicationManagement comment: ''!
!PMICommunicationManagement categoriesForClass!Kernel-Objects! !
!PMICommunicationManagement methodsFor!

chapterNumber

	^10!

englishAreaName
	^'COMMUNICATIONS'!

spanishAreaName
	^'Comunicaciones'! !
!PMICommunicationManagement categoriesFor: #chapterNumber!public! !
!PMICommunicationManagement categoriesFor: #englishAreaName!public! !
!PMICommunicationManagement categoriesFor: #spanishAreaName!public! !

