"Filed out from Dolphin Smalltalk 7"!

PMIDocumentEvent subclass: #PMICreateVersionEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMICreateVersionEvent guid: (GUID fromString: '{28ec7ac2-d139-42e6-b416-e1420d42b133}')!
PMICreateVersionEvent comment: ''!
!PMICreateVersionEvent categoriesForClass!Kernel-Objects! !
!PMICreateVersionEvent methodsFor!

eventName

	^'Creation'! !
!PMICreateVersionEvent categoriesFor: #eventName!public! !

