"Filed out from Dolphin Smalltalk 7"!

PMIManagementProcessGroup subclass: #PMIExecutingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIExecutingGroup guid: (GUID fromString: '{9f8732bf-7b4c-4e5d-a712-b8295db84f9f}')!
PMIExecutingGroup comment: ''!
!PMIExecutingGroup categoriesForClass!Kernel-Objects! !
!PMIExecutingGroup methodsFor!

englishGroupName

	^'Executing'!

spanishGroupName
	^'Ejecución'! !
!PMIExecutingGroup categoriesFor: #englishGroupName!public! !
!PMIExecutingGroup categoriesFor: #spanishGroupName!public! !

