"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMIHumanResourceManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIHumanResourceManagement guid: (GUID fromString: '{e17d1131-075a-471e-b3b0-016fecdccff7}')!
PMIHumanResourceManagement comment: ''!
!PMIHumanResourceManagement categoriesForClass!Kernel-Objects! !
!PMIHumanResourceManagement methodsFor!

chapterNumber

	^9!

englishAreaName
	^'HUMAN RESOURCE'!

spanishAreaName
	^'Recursos Humanos'! !
!PMIHumanResourceManagement categoriesFor: #chapterNumber!public! !
!PMIHumanResourceManagement categoriesFor: #englishAreaName!public! !
!PMIHumanResourceManagement categoriesFor: #spanishAreaName!public! !

