"Filed out from Dolphin Smalltalk 7"!

PMIManagementProcessGroup subclass: #PMIInitiatingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIInitiatingGroup guid: (GUID fromString: '{db794c59-f6ea-4bbe-9fed-96d4a02bd1ac}')!
PMIInitiatingGroup comment: ''!
!PMIInitiatingGroup categoriesForClass!Kernel-Objects! !
!PMIInitiatingGroup methodsFor!

englishGroupName

	^'Initiating'!

spanishGroupName
	^'Iniciación'! !
!PMIInitiatingGroup categoriesFor: #englishGroupName!public! !
!PMIInitiatingGroup categoriesFor: #spanishGroupName!public! !

