"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMIIntegrationManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIIntegrationManagement guid: (GUID fromString: '{1d0ff8cc-e370-4b3d-ba60-02c1629553ad}')!
PMIIntegrationManagement comment: ''!
!PMIIntegrationManagement categoriesForClass!Kernel-Objects! !
!PMIIntegrationManagement methodsFor!

chapterNumber

	^4!

englishAreaName
	^'INTEGRATION'!

spanishAreaName
	^'Integración'! !
!PMIIntegrationManagement categoriesFor: #chapterNumber!public! !
!PMIIntegrationManagement categoriesFor: #englishAreaName!public! !
!PMIIntegrationManagement categoriesFor: #spanishAreaName!public! !

