"Filed out from Dolphin Smalltalk 7"!

PMIProgram subclass: #PMILowerLevelProgram
	instanceVariableNames: 'parentProgram'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMILowerLevelProgram guid: (GUID fromString: '{b3abc2a5-fc62-4ee1-862c-8878bcf884f4}')!
PMILowerLevelProgram comment: ''!
!PMILowerLevelProgram categoriesForClass!Kernel-Objects! !
!PMILowerLevelProgram methodsFor!

parentProgram
	^parentProgram!

parentProgram: anObject
	parentProgram := anObject!

pathName

	^'Lower Level Program'! !
!PMILowerLevelProgram categoriesFor: #parentProgram!accessing!private! !
!PMILowerLevelProgram categoriesFor: #parentProgram:!accessing!private! !
!PMILowerLevelProgram categoriesFor: #pathName!public! !

