"Filed out from Dolphin Smalltalk 7"!

PMIManagementProcessGroup subclass: #PMIMonitoringControllingGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIMonitoringControllingGroup guid: (GUID fromString: '{2b3be8fb-e3bb-493b-a380-0d92d741ef2e}')!
PMIMonitoringControllingGroup comment: ''!
!PMIMonitoringControllingGroup categoriesForClass!Kernel-Objects! !
!PMIMonitoringControllingGroup methodsFor!

englishGroupName

	^'Monitoring and Controlling'!

spanishGroupName
	^'Seguimiento y Control'! !
!PMIMonitoringControllingGroup categoriesFor: #englishGroupName!public! !
!PMIMonitoringControllingGroup categoriesFor: #spanishGroupName!public! !

