"Filed out from Dolphin Smalltalk 7"!

PMIObject subclass: #PMIObjectDefinition
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIObjectDefinition guid: (GUID fromString: '{f630a5b5-08a7-4dee-ac12-4554724c7d3b}')!
PMIObjectDefinition comment: ''!
!PMIObjectDefinition categoriesForClass!Kernel-Objects! !
!PMIObjectDefinition methodsFor!

deliverableDescription
	^''!

getAllProcesses

	^self projectModel getAllProcesses!

isProcessDefinition

	^false! !
!PMIObjectDefinition categoriesFor: #deliverableDescription!public! !
!PMIObjectDefinition categoriesFor: #getAllProcesses!public! !
!PMIObjectDefinition categoriesFor: #isProcessDefinition!public! !

