"Filed out from Dolphin Smalltalk 7"!

PMIProcessConnector subclass: #PMIOutput
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIOutput guid: (GUID fromString: '{b5eb1dcf-cbcb-4a3f-bdbe-090dcca8948d}')!
PMIOutput comment: ''!
!PMIOutput categoriesForClass!Kernel-Objects! !
!PMIOutput methodsFor!

pathName

	^'Output'! !
!PMIOutput categoriesFor: #pathName!public! !

!PMIOutput class methodsFor!

icon

	^PMIOutputDefinition icon! !
!PMIOutput class categoriesFor: #icon!public! !

