"Filed out from Dolphin Smalltalk 7"!

PMIManagementProcessGroup subclass: #PMIPlanningGroup
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIPlanningGroup guid: (GUID fromString: '{158b5b71-dbc4-46d0-8a84-27e882df7aec}')!
PMIPlanningGroup comment: ''!
!PMIPlanningGroup categoriesForClass!Kernel-Objects! !
!PMIPlanningGroup methodsFor!

englishGroupName

	^'Planning'!

spanishGroupName
	^'Planificación'! !
!PMIPlanningGroup categoriesFor: #englishGroupName!public! !
!PMIPlanningGroup categoriesFor: #spanishGroupName!public! !

