"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMIProcurementManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIProcurementManagement guid: (GUID fromString: '{7d9022cf-6424-4a1b-8b42-c935b1194a86}')!
PMIProcurementManagement comment: ''!
!PMIProcurementManagement categoriesForClass!Kernel-Objects! !
!PMIProcurementManagement methodsFor!

chapterNumber

	^12!

englishAreaName
	^'PROCUREMENT'!

spanishAreaName
	^'Adquisiciones'! !
!PMIProcurementManagement categoriesFor: #chapterNumber!public! !
!PMIProcurementManagement categoriesFor: #englishAreaName!public! !
!PMIProcurementManagement categoriesFor: #spanishAreaName!public! !

