"Filed out from Dolphin Smalltalk 7"!

PMIArtifactDefinition subclass: #PMIProductServiceDefinition
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIProductServiceDefinition guid: (GUID fromString: '{2765859e-cf26-4c3f-9bd2-326349cf7f95}')!
PMIProductServiceDefinition comment: ''!
!PMIProductServiceDefinition categoriesForClass!Kernel-Objects! !
!PMIProductServiceDefinition methodsFor!

printType

	^self defaultLanguage printProductServiceType: self! !
!PMIProductServiceDefinition categoriesFor: #printType!public! !

!PMIProductServiceDefinition class methodsFor!

icon

	^IUnknown icon!

printType

	^self defaultLanguage printProductServiceType: self! !
!PMIProductServiceDefinition class categoriesFor: #icon!public! !
!PMIProductServiceDefinition class categoriesFor: #printType!public! !

