"Filed out from Dolphin Smalltalk 7"!

PMIDocumentEvent subclass: #PMIPublishEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIPublishEvent guid: (GUID fromString: '{48e5ec61-8dee-451e-ad0f-3cffab2a7f2b}')!
PMIPublishEvent comment: ''!
!PMIPublishEvent categoriesForClass!Kernel-Objects! !
!PMIPublishEvent methodsFor!

eventName

	^'Publish'! !
!PMIPublishEvent categoriesFor: #eventName!public! !

