"Filed out from Dolphin Smalltalk 7"!

PMIObject subclass: #PMIProcessesBuilder
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: 'default'!
PMIProcessesBuilder guid: (GUID fromString: '{f55667e1-44c7-4dd9-8541-065e326fc2cd}')!
PMIProcessesBuilder comment: ''!
!PMIProcessesBuilder categoriesForClass!Kernel-Objects! !
!PMIProcessesBuilder class methodsFor!

default
	^default!

default: anObject
	default := anObject! !
!PMIProcessesBuilder class categoriesFor: #default!accessing!private! !
!PMIProcessesBuilder class categoriesFor: #default:!accessing!private! !

