"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMIQualityManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIQualityManagement guid: (GUID fromString: '{b7b7a031-277b-4652-9bc6-a8bf4b9d69bf}')!
PMIQualityManagement comment: ''!
!PMIQualityManagement categoriesForClass!Kernel-Objects! !
!PMIQualityManagement methodsFor!

chapterNumber

	^8!

englishAreaName
	^'QUALITY'!

spanishAreaName
	^'Calidad'! !
!PMIQualityManagement categoriesFor: #chapterNumber!public! !
!PMIQualityManagement categoriesFor: #englishAreaName!public! !
!PMIQualityManagement categoriesFor: #spanishAreaName!public! !

