"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMIRiskManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIRiskManagement guid: (GUID fromString: '{1f41c9d0-4872-4b30-bbc5-2fb3faf9b54f}')!
PMIRiskManagement comment: ''!
!PMIRiskManagement categoriesForClass!Kernel-Objects! !
!PMIRiskManagement methodsFor!

chapterNumber

	^11!

englishAreaName
	^'RISK'!

spanishAreaName
	^'Riesgo'! !
!PMIRiskManagement categoriesFor: #chapterNumber!public! !
!PMIRiskManagement categoriesFor: #englishAreaName!public! !
!PMIRiskManagement categoriesFor: #spanishAreaName!public! !

