"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMIScopeManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIScopeManagement guid: (GUID fromString: '{66c2b75b-f117-4a03-bcdb-b4ad69c9532e}')!
PMIScopeManagement comment: ''!
!PMIScopeManagement categoriesForClass!Kernel-Objects! !
!PMIScopeManagement methodsFor!

chapterNumber

	^5!

englishAreaName
	^'SCOPE'!

spanishAreaName
	^'Alcance'! !
!PMIScopeManagement categoriesFor: #chapterNumber!public! !
!PMIScopeManagement categoriesFor: #englishAreaName!public! !
!PMIScopeManagement categoriesFor: #spanishAreaName!public! !

