"Filed out from Dolphin Smalltalk 7"!

PMIKnowledgeArea subclass: #PMITimeManagement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMITimeManagement guid: (GUID fromString: '{f193a182-e312-4ada-9fbf-3f5bd00bb404}')!
PMITimeManagement comment: ''!
!PMITimeManagement categoriesForClass!Kernel-Objects! !
!PMITimeManagement methodsFor!

chapterNumber

	^6!

englishAreaName
	^'TIME'!

spanishAreaName
	^'Tiempo'! !
!PMITimeManagement categoriesFor: #chapterNumber!public! !
!PMITimeManagement categoriesFor: #englishAreaName!public! !
!PMITimeManagement categoriesFor: #spanishAreaName!public! !

