"Filed out from Dolphin Smalltalk 7"!

PMIDocumentEvent subclass: #PMIUpdateVersionEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PMIUpdateVersionEvent guid: (GUID fromString: '{1179eed1-4c42-44a4-939d-9e753db2a94f}')!
PMIUpdateVersionEvent comment: ''!
!PMIUpdateVersionEvent categoriesForClass!Kernel-Objects! !
!PMIUpdateVersionEvent methodsFor!

eventName

	^'Update'! !
!PMIUpdateVersionEvent categoriesFor: #eventName!public! !

